authors:
  Khaled Abdelfattah:
    name: Khaled Abdelfattah
    description: Sofware Technical Writer
    avatar: https://raw.githubusercontent.com/khaled-ahmed-nagwa/testingmkdoc/main/docs/assets/images/favicon.png
